name: Release Windows App

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "C:\Users\runneradmin\.bun\bin" >> $GITHUB_PATH
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Dependencies
        run: bun install
      - name: Build and Release Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v0.1.0
          releaseName: "Release v0.1.0"
          releaseBody: "Windows-only Tauri app with Bun."
          releaseDraft: true
          targets: 'exe'